version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    # - revive

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    check-shadowing: true
