version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose     # Checks that HTTP bodies are closed
    - noctx         # Checks that http requests have context
    - revive        # Drop-in replacement for golint
    - gocritic      # Provides diagnostics in Go code
    - misspell      # Finds commonly misspelled English words

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    check-shadowing: true
