steps:
  # Run Linting
  - name: 'golangci/golangci-lint:v2.7.2'
    args: ['golangci-lint', 'run', '--timeout=5m', '--verbose']

  # Build and Push using Kaniko for layer caching and faster builds
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/sketchnote-artist:$COMMIT_SHA'
      - '--cache=true'
      - '--cache-ttl=24h'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/sketchnote-artist:$COMMIT_SHA'
      - '--region'
      - '$_REGION'

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
